apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: gosbench
data:
  # prometheus.rules: |-
  #   groups:
  #   - name: devopscube demo alert
  #     rules:
  #     - alert: High Pod Memory
  #       expr: sum(container_memory_usage_bytes) > 1
  #       for: 1m
  #       labels:
  #         severity: slack
  #       annotations:
  #         summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    # alerting:
    #   alertmanagers:
    #   - scheme: http
    #     static_configs:
    #     - targets:
    #       - "alertmanager.gosbench.svc:9093"

    scrape_configs:
      - job_name: 'gosbench-workers'
        scrape_interval: 3s
        scrape_timeout: 3s
        static_configs:
          - targets: ['10.3.9.221:7777']
          - targets: ['10.3.9.222:7777']
          - targets: ['10.3.9.223:7777']
          - targets: ['10.3.9.224:7777']
          - targets: ['10.3.9.225:7777']
          - targets: ['10.3.9.226:7777']
          - targets: ['10.3.9.227:7777']
          - targets: ['10.3.9.228:7777']
          - targets: ['10.3.9.229:7777']
          - targets: ['10.3.9.230:7777']

      - job_name: 'node-exporters'
        scrape_interval: 3s
        scrape_timeout: 3s
        static_configs:
          - targets: ['10.3.9.221:9100']
          - targets: ['10.3.9.222:9100']
          - targets: ['10.3.9.223:9100']
          - targets: ['10.3.9.224:9100']
          - targets: ['10.3.9.225:9100']
          - targets: ['10.3.9.226:9100']
          - targets: ['10.3.9.227:9100']
          - targets: ['10.3.9.228:9100']
          - targets: ['10.3.9.229:9100']
          - targets: ['10.3.9.230:9100']
