apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: gosbench
data:
  # prometheus.rules: |-
  #   groups:
  #   - name: devopscube demo alert
  #     rules:
  #     - alert: High Pod Memory
  #       expr: sum(container_memory_usage_bytes) > 1
  #       for: 1m
  #       labels:
  #         severity: slack
  #       annotations:
  #         summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    # alerting:
    #   alertmanagers:
    #   - scheme: http
    #     static_configs:
    #     - targets:
    #       - "alertmanager.gosbench.svc:9093"

    scrape_configs:
      - job_name: 'gosbench-worker'
        scrape_interval: 3s
        scrape_timeout: 3s
        static_configs:
          - targets:
            - 10.3.11.81:7777
            - 10.3.11.82:7777
            - 10.3.11.83:7777
